[default.deploy.parameters]
stack_name = "fl-coordinator"
resolve_s3 = true
s3_prefix = "fl-coordinator"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
